version: '3.7'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  teacheress:
    build: ./
    environment:
      - REDIS_TYPE=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    command: uvicorn teacheress.main:app --reload --workers 1 --host 0.0.0.0 --port 8000